### ISSUE TITLE
Use number as key

### ISSUE THREAD

**Issue by suyu34** [nbubna/store#25]
When I use number to get value, it go to the wrong way.

e.g.
var cache = store.namespace('test')
cache(1, true)
console.log(cache(1))

In the store function, it just charge the string type, but sometimes the key will be number.
Should I pull request to solve this issue?

**Comment by nbubna** [comment]
The value is stored just fine. Try ```console.log(cache.get(1));```

The ```cache(key)``` shortcut is treating the single, non-string parameter as an object and passing it off to the ```setAll(values)``` function instead of ```get(key)```.

Using non-string keys is not something store is designed to fully support. I'd be happy to review and consider a pull request that changes that, especially if it doesn't require a lot of changes.

**Comment by nbubna** [comment]
Thanks for the PR. Works for me. :)
