### ISSUE TITLE
[question] Asynchronous read/write support?

### ISSUE THREAD

**Issue by nathanph** [nbubna/store#30]
The documentation doesn't specify how this module manages asynchronous read/write (e.g., `chrome.storage.local`).

Also is there a way to specify a hierarchy of storage fallback options within the module?

**Comment by nbubna** [comment]
Sorry, i didn't realize chrome.storage.local was async. I made the assumption it was an implementation of the web storage interface (https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface).

And no, if a full fallback hierarchy makes sense for your app, that should probably be manually handled, so as to be clear what is happening. We have support for "fake storage" as a singular backup, because the primary user story is that, for webapps, truly persistent local storage is an unreliable bonus by definition. No app should ever depend on the presence of cached values, but always be prepared to encounter an emptied cache. But also, no app should break if localStorage happens to be unavailable. Thus we can safely fake it.

I can imagine, though, with browser extension using chrome.storage.local, those rules may be substantially different. It may be that store2 is simply not the best option for such environments.

**Comment by nbubna** [comment]
Closing due to lack of feedback on last response and likelihood that this is out of scope.
