### ISSUE TITLE
Request for memStorage

### ISSUE THREAD

**Issue by adrianvoica** [nbubna/store#69]
Please consider adding support for a temporary (dies on page reloads) memory storage object (dubbed it 'memStorage' :)). 
This way, store would become the go-to state repository library for any app and any scenario, be it vanilla or otherwise. Redux no more. 
Thanks!

**Comment by nbubna** [comment]
Interesting notion. This is essentially supported already, though not explicitly. In any environment where ```localStorage``` or ```sessionStorage``` is not available, store will create a fallback that is non-persistent, kept only in memory and lost on page reload. That's what the ```store.isFake()``` method identifies. So, to create your own page-only storage area, you just need to do this:
```
store.page = store.area('page');
```

That said, i can see how a more official support, perhaps even making this automatically, as we do ```store.local``` and ```store.session```. I might need to find another name for ```isFake()``` though, as that is a bit negative for something officially supported. Maybe just ```isPage()```?

**Comment by adrianvoica** [comment]
Great! So, how about isTemp() then? since it's temporary... just sayin'. Anyway, a memStorage or tempStorage or whatever, as an official 'driver' would make this incredibly useful. Keep up the good work!

**Comment by nbubna** [comment]
sessionStorage is also temporary, so it'd be weird to return false for that. Maybe isFallback()? Because the reason for the function is to identify when we're not actually using localStorage or sessionStorage. Of course, isPage() works well for that too.

**Comment by adrianvoica** [comment]
Well, everything is more or less temporary. Unrelated to the problem at hand, I am working on a project with Page.js (very small and powerful router), and isPage() sound rather confusing mixed within the code with page() calls :). Anyway, I'm just a humble user of 'store', so, I can only suggest stuff. In this regard, I'd pick a more descriptive name, like isShallow() or something along that line. It's your call. I just would like to have that functionality built as an official alternative to the local and session drivers. Thanks a lot for your time!

**Comment by nbubna** [comment]
Ok, worked on this some today. I've decided isFake() is just fine, so long as it only returns true when using a page-scope storage as a fallback for localStorage and/or sessionStorage, and false otherwise. I've already implemented this cleanly.

The only decision left is whether to call this ```store.page``` or ```store.document``` (or something else, if you have a better idea). I'm leaning toward "page", but am undecided.

Also, as a result of this, the 2nd, ```noSession``` argument for the ```namespace()``` function is a bit out of date. I've long wished i had made namespace() default to *not* replicating the area names on the namespaced store instance, but unless i want to do a major version bump, that ship has sailed. I think instead, i will change its name to "singleArea", continue to replicate all the areas on the namespaced instances, and remove it from the documentation (as close to official deprecation as can be done).

**Comment by adrianvoica** [comment]
Hey Nathan, that's incredible news. A nice word just popped in my mind that might fit de description: how about 'isTransient()' ? Godspeed.

**Comment by nbubna** [comment]
Nah, isFake() fits and already exists. Thanks, though.

**Comment by nbubna** [comment]
Ok, it's in v2.10.0
