### ISSUE TITLE
Marshalling 'undefined' property

### ISSUE THREAD

**Issue by PlkMarudny** [nbubna/store#86]
If a stored value is undefined, it is store as a string 'undefined'. Would it be feasible to marshall/unmarshall undefined properly? Possibly null value as well.

**Comment by nbubna** [comment]
Hmm.  How would we tell they wanted it to be the value `undefined` instead of the string `"undefined"`? What if the next person says, "Hey, i need to store the string 'undefined', but it keeps getting turned into the value `undefined`?" If we have to start storing the type with the value, things get icky. And how are you storing `undefined`? It must be with a different library or directly in the localStorage/sessionStorage interface, because store2 would refuse to persist it if you passed the value `undefined`. It does handle the value `null`, just fine, by the way. You can `store('foo', null)` and it will return `null` for `store('foo')` and return `true` for `store.has('foo')`. But we don't support turning `"undefined"` into `undefined`, and i'm not convinced we should.

**Comment by PlkMarudny** [comment]
Yes, this sounds reasonable. At the moment I use a simple custom function to unmarshall the string "undefined" into undefined, but I know that I store numbers under the key, so no conflicts appear.

**Comment by nbubna** [comment]
Yeah, a custom function or plugin sounds like the best move here.
